Models/CurriculoViewModel.cs
using System;

namespace Curriculos.Models
{
    public class CurriculoViewModel
    {
        public String Nome { get; set; }
        public String Cpf { get; set; }
        public DateTime DataNascimento { get; set; }
        public String Endereco { get; set; }
        public String Telefone { get; set; }
        public String Email { get; set; }
        public double? Salario { get; set; }
        public String Cargo { get; set; }
        public String[] Formacoes { get; set; }
        public String[] Experiencias { get; set; }
        public String[] Idiomas { get; set; }

        public CurriculoViewModel()
        {
            Formacoes = new string[5];
            Experiencias = new string[3];
            Idiomas = new string[3];
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Curriculos.Models
{
    public class ErrorViewModel
    {
        public ErrorViewModel(string erro)
        {
            this.Erro = erro;
        }
        public ErrorViewModel()
        {
        }
        public string Erro { get; set; }
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CurriculoController.cs
using Microsoft.AspNetCore.Mvc;
using Curriculos.DAO;
using Curriculos.Models;
using System.Collections.Generic;
using System;
using System.Security.Cryptography.X509Certificates;

namespace Curriculos.Controllers
{
    public class CurriculoController : Controller
    {
        public IActionResult Index()
        {
            try
            {
                CurriculoDAO curriculoDAO = new CurriculoDAO();
                List<CurriculoViewModel> curriculos = curriculoDAO.Listar();
                return View(curriculos);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult Create()
        {
            try
            {
                CurriculoViewModel curriculo = new CurriculoViewModel();
                curriculo.DataNascimento = DateTime.Now;
                return View("Formulario", curriculo);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }

        }

        public IActionResult Salvar(CurriculoViewModel curriculo)
        {
            try
            {
                CurriculoDAO curriculoDAO = new CurriculoDAO();
                curriculoDAO.Inserir(curriculo);
                return RedirectToAction("index");
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }

        }
        public IActionResult Exibicao(string cpf)
        {
            try
            {
                CurriculoDAO curriculoDAO = new CurriculoDAO();
                CurriculoViewModel curriculo= curriculoDAO.Consultar(cpf);
                return View("Exibicao", curriculo);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Curriculos.Models;

namespace Curriculos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Curriculo/Exibicao.cshtml
@model CurriculoViewModel
@{
    ViewData["Title"] = Model.Nome;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="curriculo">
    <h1 id="nome">@Model.Nome</h1>

    <h3 class="subtitulo">Dados Pessoais</h3>

    <ul class="curriculo dados-pessoais">
        <li>CPF: @Model.Cpf</li>
        <li>Data de Nascimento: @Model.DataNascimento.ToString("d")</li>
        <li>Endereço: @Model.Endereco</li>
        <li>Telefone: @Model.Telefone</li>
        <li>E-mail: <a href="mailto:@Model.Email">@Model.Email</a></li>
    </ul>

    <p class="curriculo objetivo">Cargo Pretendido: <strong>@Model.Cargo</strong></p>
    <p class="curriculo objetivo">Pretensão Salarial: @Model.Salario.ToString()</p>

    <h3 class="curriculo subtitulo">Cursos e Formação Acadêmica</h3>
    <ul class="curriculo lista">
        @foreach (string formacao in Model.Formacoes)
        {
            if (formacao != "" && formacao != null)
            {
                <li>@formacao</li>
            }
        }
    </ul>

    <h3 class="curriculo subtitulo">Experiências Profissionais</h3>
    <ul class="curriculo lista">
        @foreach (string experiencia in Model.Experiencias)
        {
            if (experiencia != "" && experiencia != null)
            {
                <li>@experiencia</li>
            }
        }
    </ul>

    <h3 class="curriculo subtitulo">Idiomas</h3>
    <ul class="curriculo lista">
        @foreach (string idioma in Model.Idiomas)
        {
            if (idioma != "" && idioma != null)
            {
                <li>@idioma</li>
            }
        }
    </ul>
</div>

Views/Curriculo/Formulario.cshtml
@model CurriculoViewModel
@{
    ViewData["Title"] = "Cadastro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastro de Currículo</h2>

<form action="Salvar" method="post">
    <label for="Nome" class="control-label">Nome</label>
    <input type="text" name="Nome" value="@Model.Nome" required/>
    <br />

    <label for="Cpf" class="control-label">CPF</label>
    <input type="text" name="Cpf" value="@Model.Cpf" required/>
    <br />

    <label for="DataNascimento" class="control-label">Data de Nascimento</label>
    <input type="date" name="DataNascimento" value="@Model.DataNascimento.ToString("yyyy-MM-dd")" />
    <br />

    <label for="Endereco" class="control-label">Endereço</label>
    <input type="text" name="Endereco" value="@Model.Endereco" />
    <br />

    <label for="Telefone" class="control-label">Telefone</label>
    <input type="tel" name="Telefone" value="@Model.Telefone" />
    <br />

    <label for="Email" class="control-label">E-mail</label>
    <input type="email" name="Email" value="@Model.Email" />
    <br />

    <label for="Salario" class="control-label">Pretensão de Salário</label>
    <input type="text" name="Salario" value="@Model.Salario" />
    <br />

    <label for="Cargo" class="control-label">Cargo Pretendido</label>
    <input type="text" name="Cargo" value="@Model.Cargo" />
    <br />

    <label for="Formacao1" class="control-label">Formação 1</label>
    <br />
    <input type="text" name="Formacoes[0]" value="@Model.Formacoes[0]" required/>
    <br />
    <input type="text" name="Formacoes[1]" value="@Model.Formacoes[1]" />
    <br />
    <input type="text" name="Formacoes[2]" value="@Model.Formacoes[2]" />
    <br />
    <input type="text" name="Formacoes[3]" value="@Model.Formacoes[3]" />
    <br />
    <input type="text" name="Formacoes[4]" value="@Model.Formacoes[4]" />
    <br />

    <label for="Experiencias" class="control-label">Experiências profissionais</label>
    <br />
    <input type="text" name="Experiencias[0]" value="@Model.Experiencias[0]" />
    <br />
    <input type="text" name="Experiencias[1]" value="@Model.Experiencias[1]" />
    <br />
    <input type="text" name="Experiencias[2]" value="@Model.Experiencias[2]" />
    <br />

    <label for="Idiomas" class="control-label">Idiomas</label>
    <br />
    <input type="text" name="Idiomas[0]" value="@Model.Idiomas[0]" />
    <br />
    <input type="text" name="Idiomas[1]" value="@Model.Idiomas[1]" />
    <br />
    <input type="text" name="Idiomas[2]" value="@Model.Idiomas[2]" />
    <br />

    <input type="submit" value="Salvar Currículo" />

</form>

Views/Curriculo/Index.cshtml
@model List<CurriculoViewModel>
@{
    ViewData["Title"] = "Página Inicial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Currículos</h2>

<a href="/curriculo/create">Novo currículo</a>

<table class="table table-responsive">
    <tr>
        <th>Ações</th>
        <th>Nome</th>
        <th>CPF</th>
    </tr>
    @foreach (var curriculo in Model)
    {
        <tr>
            <td><a href="/curriculo/Exibicao?cpf=@curriculo.Cpf">Exibir</a> </td>
            <td>@curriculo.Nome</td>
            <td>@curriculo.Cpf</td>
        </tr>
    }
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Currículos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Curriculo" asp-action="Index">Currículos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curriculo" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curriculo" asp-action="Create">Cadastrar Currículo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Currículos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>